# Generated by Django 5.2 on 2026-07-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='chef_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
