# Generated by Django 5.2 on 2026-07-17 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=50)),
                ('choices', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('service', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('network', models.BooleanField(default=True)),
                ('delivery', models.BooleanField(default=True)),
                ('rating', models.FloatField()),
                ('hours', models.TimeField()),
                ('price', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chefs.chef')),
            ],
            options={
                'ordering': ['-list_date'],
                'indexes': [models.Index(fields=['list_date'], name='listings_li_list_da_153ce3_idx')],
            },
        ),
    ]
