# Generated by Django 5.2 on 2026-07-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_choices_listing_curisine_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='curisine_choices',
            new_name='cuisine_choices',
        ),
    ]
