# Generated by Django 5.2 on 2026-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_curisine_choices_listing_cuisine_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cuisine_choices',
            field=models.CharField(choices=[('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Thai', 'Thai'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Korean', 'Korean'), ('Vietnamese', 'Vietnamese')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(choices=[('Islands', 'Islands'), ('KT', 'Kwun Tong'), ('North', 'North'), ('SK', 'Sai Kung'), ('ST', 'Sha Tin'), ('TP', 'Tai Po'), ('TW', 'Tsuen Wan'), ('TM', 'Tuen Mun'), ('YL', 'Yuen Long'), ('KC', 'Kowloon City'), ('SSP', 'Sham Shui Po'), ('WTS', 'Wong Tai Sin'), ('YTM', 'Yau Tsim Mong'), ('CW', 'Central & Western'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('WC', 'Wan Chai')], default='', max_length=50),
        ),
    ]
