# Generated by Django 5.2 on 2026-08-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_cuisine_choices_alter_listing_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='closing_hours',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='specialty',
        ),
        migrations.AddField(
            model_name='listing',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='listings.menu'),
        ),
    ]
