# Generated by Django 5.2 on 2026-08-03 09:03

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_menu_listing_closing_hours_remove_listing_specialty_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='room_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='room_type',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Rooms'),
        ),
    ]
