# Generated by Django 5.2 on 2026-07-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='photo',
            new_name='portrait',
        ),
    ]
