# Generated by Django 5.2 on 2026-07-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_rename_description_chef_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='hire_date',
            new_name='bire_date',
        ),
    ]
