# Generated by Django 5.2 on 2026-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('portrait', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(choices=[('Editer', 'Editer'), ('Manager', 'Manager'), ('Chef Writer', 'Chef Writer')], default='', max_length=100)),
            ],
        ),
    ]
