# Generated by Django 5.2 on 2026-07-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
